import { useState } from 'react';
import { API, useAuth } from '../App.jsx';
import { ScoreCard } from '../components/ScoreCard.jsx';
import { FindingsList } from '../components/ScoreCard.jsx';
import { RecentScans } from '../components/ScoreCard.jsx';

export default function Scanner({ onNav }) {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const { user } = useAuth();

if (!user) {
    return (
      <div className="scanner-page">
        <div className="scanner-hero">
          <h1 className="hero-title"><span className="hero-accent">Analyze</span> your web posture</h1>
          <p className="hero-sub">Security · Performance · Compliance · CDN — scored in seconds, powered by AI at the edge.</p>
          <div className="auth-gate">
            <p className="auth-gate-msg">Create a free account to start scanning.</p>
            <div className="auth-gate-btns">
              <button className="scan-btn" style={{borderRadius:'10px',padding:'14px 32px'}} onClick={() => onNav('register')}>Get started free</button>
              <button className="nav-btn-ghost" onClick={() => onNav('login')}>Sign in</button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const scan = async (e) => {
    e.preventDefault();
    setError(null); setResult(null); setLoading(true);
    let target = url.trim();
    if (!target.startsWith('http')) target = 'https://' + target;
    try {
      const res = await fetch(`${API}/scan`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: target }) });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Scan failed');
      setResult(data);
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  };

  const grade = (s) => s >= 80 ? 'good' : s >= 50 ? 'warn' : 'poor';

  const downloadPDF = (r) => {
    const lines = [];
    lines.push("EDGEPOSTURE SCAN REPORT");
    lines.push("=".repeat(60));
    lines.push("");
    lines.push("URL: " + (r.finalUrl || r.url));
    lines.push("Scanned: " + new Date(r.scannedAt).toLocaleString());
    lines.push("TTFB: " + r.ttfb + "ms");
    lines.push("");
    lines.push("OVERALL SCORE: " + r.overallScore + " / 100");
    lines.push("");
    lines.push("CATEGORY SCORES");
    lines.push("-".repeat(40));
    lines.push("Security:    " + r.scores.security + " / 100");
    lines.push("Performance: " + r.scores.performance + " / 100");
    lines.push("Compliance:  " + r.scores.compliance + " / 100");
    lines.push("CDN Posture: " + r.scores.cdn + " / 100");
    lines.push("");
    lines.push("AI SUMMARY");
    lines.push("-".repeat(40));
    const words = (r.summary || "").split(" ");
    let line = "";
    words.forEach(w => {
      if ((line + w).length > 70) { lines.push(line.trim()); line = ""; }
      line += w + " ";
    });
    if (line.trim()) lines.push(line.trim());
    lines.push("");
    lines.push("FINDINGS");
    lines.push("-".repeat(40));
    (r.findings || []).forEach((f, i) => {
      lines.push((i+1) + ". [" + (f.severity||"").toUpperCase() + "] " + f.title);
      const dwords = (f.detail || "").split(" ");
      let dline = "   ";
      dwords.forEach(w => {
        if ((dline + w).length > 72) { lines.push(dline.trim()); dline = "   "; }
        dline += w + " ";
      });
      if (dline.trim()) lines.push(dline.trim());
      lines.push("");
    });
    lines.push("RECOMMENDATIONS");
    lines.push("-".repeat(40));
    (r.recommendations || []).forEach((rec, i) => {
      lines.push((i+1) + ". [P" + rec.priority + "] " + rec.title);
      const rwords = (rec.detail || "").split(" ");
      let rline = "   ";
      rwords.forEach(w => {
        if ((rline + w).length > 72) { lines.push(rline.trim()); rline = "   "; }
        rline += w + " ";
      });
      if (rline.trim()) lines.push(rline.trim());
      if (rec.edgeFix) lines.push("   Edge fix: " + rec.edgeFix);
      lines.push("");
    });
    lines.push("=".repeat(60));
    lines.push("Generated by EdgePosture · edgepostureapp.com");
    lines.push("=".repeat(60));
    const text = lines.join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const domain = (r.finalUrl || r.url).replace(/https?:\/\//, "").replace(/\//g, "_");
    a.href = url;
    a.download = "edgeposture-" + domain + "-" + new Date().toISOString().slice(0,10) + ".txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="scanner-page">
      <div className="scanner-hero">
        <h1 className="hero-title"><span className="hero-accent">Analyze</span> your web posture</h1>
        <p className="hero-sub">Security · Performance · Compliance · CDN — scored in seconds, powered by AI at the edge.</p>
        <form className="scan-form" onSubmit={scan}>
          <div className="scan-input-wrap">
            <span className="scan-prefix">https://</span>
            <input className="scan-input" type="text" value={url} onChange={e => setUrl(e.target.value)} placeholder="example.com" autoFocus required />
            <button className="scan-btn" type="submit" disabled={loading}>{loading ? <span className="spinner" /> : 'Scan'}</button>
          </div>
        </form>
        {error && <div className="scan-error">{error}</div>}
      </div>
      {loading && <div className="scanning-state"><div className="scan-pulse" /><p>Analyzing {url}...</p></div>}
      {result && (
        <div className="results-wrap">
          <div className="results-header">
            <div>
              <h2 className="results-url">{result.finalUrl || result.url}</h2>
              <p className="results-meta">Scanned {new Date(result.scannedAt).toLocaleString()} · TTFB {result.ttfb}ms{result.cached ? ' · cached' : ''}</p>
            </div>
            <div style={{display:'flex',alignItems:'center',gap:'12px'}}>
              <button className="pdf-btn" onClick={() => downloadPDF(result)}>Download PDF</button>
              <div className={`overall-score score-${grade(result.overallScore)}`}>
                <span className="score-num">{result.overallScore}</span>
                <span className="score-label">/ 100</span>
              </div>
            </div>
          </div>
          <div className="score-grid">
            <ScoreCard label="Security" score={result.scores.security} icon="🔒" />
            <ScoreCard label="Performance" score={result.scores.performance} icon="⚡" />
            <ScoreCard label="Compliance" score={result.scores.compliance} icon="✅" />
            <ScoreCard label="CDN Posture" score={result.scores.cdn} icon="🌐" />
          </div>
          <div className="summary-card"><h3>AI Summary</h3><p>{result.summary}</p></div>
          <div className="findings-recs">
            <FindingsList findings={result.findings} title="Findings" />
            <FindingsList findings={result.recommendations} title="Recommendations" isRecs={true} />
          </div>
        </div>
      )}
      {!result && !loading && <RecentScans />}
    </div>
  );
}