content = open('C:/Users/miked/edgeposture/edgepostureapp/src/pages/Scanner.jsx', encoding='utf-8').read()

# Add PDF download function and button to the results section
old_results_header = '''          <div className="results-header">
            <div>
              <h2 className="results-url">{result.finalUrl || result.url}</h2>
              <p className="results-meta">Scanned {new Date(result.scannedAt).toLocaleString()} · TTFB {result.ttfb}ms{result.cached ? ' · cached' : ''}</p>
            </div>
            <div className={`overall-score score-${grade(result.overallScore)}`}>
              <span className="score-num">{result.overallScore}</span>
              <span className="score-label">/ 100</span>
            </div>
          </div>'''

new_results_header = '''          <div className="results-header">
            <div>
              <h2 className="results-url">{result.finalUrl || result.url}</h2>
              <p className="results-meta">Scanned {new Date(result.scannedAt).toLocaleString()} · TTFB {result.ttfb}ms{result.cached ? ' · cached' : ''}</p>
            </div>
            <div style={{display:'flex',alignItems:'center',gap:'12px'}}>
              <button className="pdf-btn" onClick={() => downloadPDF(result)}>Download PDF</button>
              <div className={`overall-score score-${grade(result.overallScore)}`}>
                <span className="score-num">{result.overallScore}</span>
                <span className="score-label">/ 100</span>
              </div>
            </div>
          </div>'''

content = content.replace(old_results_header, new_results_header)

# Add downloadPDF function before the return statement
old_return = '''  const grade = (s) => s >= 80 ? \'good\' : s >= 50 ? \'warn\' : \'poor\';'''

new_return = '''  const grade = (s) => s >= 80 ? \'good\' : s >= 50 ? \'warn\' : \'poor\';

  const downloadPDF = (r) => {
    const lines = [];
    lines.push("EDGEPOSTURE SCAN REPORT");
    lines.push("=".repeat(60));
    lines.push("");
    lines.push("URL: " + (r.finalUrl || r.url));
    lines.push("Scanned: " + new Date(r.scannedAt).toLocaleString());
    lines.push("TTFB: " + r.ttfb + "ms");
    lines.push("");
    lines.push("OVERALL SCORE: " + r.overallScore + " / 100");
    lines.push("");
    lines.push("CATEGORY SCORES");
    lines.push("-".repeat(40));
    lines.push("Security:    " + r.scores.security + " / 100");
    lines.push("Performance: " + r.scores.performance + " / 100");
    lines.push("Compliance:  " + r.scores.compliance + " / 100");
    lines.push("CDN Posture: " + r.scores.cdn + " / 100");
    lines.push("");
    lines.push("AI SUMMARY");
    lines.push("-".repeat(40));
    const words = (r.summary || "").split(" ");
    let line = "";
    words.forEach(w => {
      if ((line + w).length > 70) { lines.push(line.trim()); line = ""; }
      line += w + " ";
    });
    if (line.trim()) lines.push(line.trim());
    lines.push("");
    lines.push("FINDINGS");
    lines.push("-".repeat(40));
    (r.findings || []).forEach((f, i) => {
      lines.push((i+1) + ". [" + (f.severity||"").toUpperCase() + "] " + f.title);
      const dwords = (f.detail || "").split(" ");
      let dline = "   ";
      dwords.forEach(w => {
        if ((dline + w).length > 72) { lines.push(dline.trim()); dline = "   "; }
        dline += w + " ";
      });
      if (dline.trim()) lines.push(dline.trim());
      lines.push("");
    });
    lines.push("RECOMMENDATIONS");
    lines.push("-".repeat(40));
    (r.recommendations || []).forEach((rec, i) => {
      lines.push((i+1) + ". [P" + rec.priority + "] " + rec.title);
      const rwords = (rec.detail || "").split(" ");
      let rline = "   ";
      rwords.forEach(w => {
        if ((rline + w).length > 72) { lines.push(rline.trim()); rline = "   "; }
        rline += w + " ";
      });
      if (rline.trim()) lines.push(rline.trim());
      if (rec.edgeFix) lines.push("   Edge fix: " + rec.edgeFix);
      lines.push("");
    });
    lines.push("=".repeat(60));
    lines.push("Generated by EdgePosture · edgepostureapp.com");
    lines.push("=".repeat(60));
    const text = lines.join("\\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const domain = (r.finalUrl || r.url).replace(/https?:\\/\\//, "").replace(/\\//g, "_");
    a.href = url;
    a.download = "edgeposture-" + domain + "-" + new Date().toISOString().slice(0,10) + ".txt";
    a.click();
    URL.revokeObjectURL(url);
  };'''

content = content.replace(old_return, new_return)

with open('C:/Users/miked/edgeposture/edgepostureapp/src/pages/Scanner.jsx', 'w', encoding='utf-8') as f:
    f.write(content)
print('PDF download added')