lines = []
lines.append('<!doctype html>')
lines.append('<html lang="en">')
lines.append('<head>')
lines.append('<meta charset="UTF-8"/>')
lines.append('<meta name="viewport" content="width=device-width,initial-scale=1.0"/>')
lines.append('<title>EdgePosture AI Assistant</title>')
lines.append('<link rel="preconnect" href="https://fonts.googleapis.com"/>')
lines.append('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>')
lines.append('<link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"/>')
lines.append('<style>')
lines.append(':root{--bg:#0a0c10;--bg2:#111318;--bg3:#181b22;--border:rgba(255,255,255,0.08);--border2:rgba(255,255,255,0.14);--text:#e8eaf0;--text2:#8b8fa8;--text3:#555870;--accent:#4f7bff;--accent2:#7c9fff;--good:#22c55e;--poor:#ef4444}')
lines.append('*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}')
lines.append('html,body{height:100%;overflow:hidden}')
lines.append('body{font-family:"DM Sans",sans-serif;background:var(--bg);color:var(--text);display:flex;flex-direction:column}')
lines.append('body::before{content:"";position:fixed;inset:0;background-image:linear-gradient(rgba(79,123,255,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(79,123,255,0.03) 1px,transparent 1px);background-size:60px 60px;pointer-events:none;z-index:0}')
lines.append('nav{position:relative;z-index:10;display:flex;align-items:center;gap:1.5rem;padding:0 1.5rem;height:56px;background:rgba(10,12,16,0.95);border-bottom:1px solid var(--border);flex-shrink:0}')
lines.append('.nav-brand{display:flex;align-items:center;gap:8px;text-decoration:none}')
lines.append('.nav-logo{width:28px;height:28px;background:var(--accent);border-radius:7px;display:flex;align-items:center;justify-content:center;font-family:"Space Mono",monospace;font-size:11px;font-weight:700;color:#fff}')
lines.append('.nav-title{font-size:14px;font-weight:600;color:var(--text)}')
lines.append('.nav-badge{font-size:10px;padding:2px 8px;border-radius:4px;background:rgba(79,123,255,0.12);color:var(--accent2);font-family:"Space Mono",monospace;text-transform:uppercase;letter-spacing:0.04em}')
lines.append('.nav-right{margin-left:auto;display:flex;align-items:center;gap:10px}')
lines.append('.rate-info{font-size:11px;color:var(--text3)}')
lines.append('.nav-link{color:var(--text2);text-decoration:none;font-size:13px;padding:5px 10px;border-radius:6px;transition:color 0.15s,background 0.15s;background:none;border:none;cursor:pointer;font-family:"DM Sans",sans-serif}')
lines.append('.nav-link:hover{color:var(--text);background:rgba(255,255,255,0.06)}')
lines.append('.app-body{flex:1;display:flex;overflow:hidden;position:relative;z-index:1}')
lines.append('.sidebar{width:240px;flex-shrink:0;background:var(--bg2);border-right:1px solid var(--border);display:flex;flex-direction:column;overflow:hidden}')
lines.append('.sidebar-header{padding:12px 12px 8px;border-bottom:1px solid var(--border);flex-shrink:0}')
lines.append('.new-chat-btn{width:100%;background:var(--accent);color:#fff;border:none;padding:8px 12px;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;font-family:"DM Sans",sans-serif;transition:opacity 0.15s;display:flex;align-items:center;justify-content:center;gap:6px}')
lines.append('.new-chat-btn:hover{opacity:0.85}')
lines.append('.sidebar-label{font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:var(--text3);padding:10px 12px 4px;font-family:"Space Mono",monospace}')
lines.append('.sessions-list{flex:1;overflow-y:auto;padding:4px 8px 8px}')
lines.append('.sessions-list::-webkit-scrollbar{width:3px}.sessions-list::-webkit-scrollbar-thumb{background:var(--border2);border-radius:2px}')
lines.append('.session-item{display:flex;align-items:center;gap:6px;padding:7px 8px;border-radius:7px;cursor:pointer;transition:background 0.12s;group:true}')
lines.append('.session-item:hover{background:rgba(255,255,255,0.05)}')
lines.append('.session-item.active{background:rgba(79,123,255,0.1);border:1px solid rgba(79,123,255,0.2)}')
lines.append('.session-item.active .session-title{color:var(--accent2)}')
lines.append('.session-title{flex:1;font-size:12px;color:var(--text2);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;line-height:1.4}')
lines.append('.session-del{background:none;border:none;color:var(--text3);cursor:pointer;font-size:14px;padding:2px 4px;border-radius:4px;opacity:0;transition:opacity 0.15s,color 0.15s;flex-shrink:0}')
lines.append('.session-item:hover .session-del{opacity:1}')
lines.append('.session-del:hover{color:var(--poor);opacity:1}')
lines.append('.session-date{font-size:10px;color:var(--text3);white-space:nowrap}')
lines.append('.sessions-empty{padding:1rem 8px;font-size:12px;color:var(--text3);text-align:center}')
lines.append('.chat-main{flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0}')
lines.append('.messages{flex:1;overflow-y:auto;padding:1.5rem;display:flex;flex-direction:column;gap:1rem}')
lines.append('.messages::-webkit-scrollbar{width:4px}.messages::-webkit-scrollbar-thumb{background:var(--border2);border-radius:2px}')
lines.append('.msg{display:flex;gap:10px;max-width:100%}')
lines.append('.msg.user{flex-direction:row-reverse}')
lines.append('.msg-avatar{width:28px;height:28px;border-radius:7px;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;flex-shrink:0;font-family:"Space Mono",monospace}')
lines.append('.msg.assistant .msg-avatar{background:var(--accent);color:#fff}')
lines.append('.msg.user .msg-avatar{background:var(--bg3);color:var(--text2);border:1px solid var(--border2)}')
lines.append('.msg-bubble{background:var(--bg3);border:1px solid var(--border);border-radius:12px;padding:10px 14px;font-size:14px;line-height:1.65;max-width:calc(100% - 40px)}')
lines.append('.msg.user .msg-bubble{background:rgba(79,123,255,0.1);border-color:rgba(79,123,255,0.2);color:var(--text)}')
lines.append('.msg.assistant .msg-bubble{color:var(--text2)}')
lines.append('.msg.blocked .msg-bubble{background:rgba(239,68,68,0.08);border-color:rgba(239,68,68,0.2);color:var(--poor)}')
lines.append('.msg-bubble code{background:var(--bg2);border:1px solid var(--border);padding:1px 5px;border-radius:3px;font-family:"Space Mono",monospace;font-size:12px;color:var(--accent2)}')
lines.append('.msg-bubble pre{background:var(--bg2);border:1px solid var(--border);border-radius:8px;padding:10px 12px;overflow-x:auto;margin:8px 0;font-family:"Space Mono",monospace;font-size:12px;color:var(--text);line-height:1.5}')
lines.append('.msg-bubble pre code{background:none;border:none;padding:0;color:var(--text)}')
lines.append('.msg-bubble p{margin-bottom:6px}.msg-bubble p:last-child{margin-bottom:0}')
lines.append('.msg-bubble ul,.msg-bubble ol{padding-left:1.25rem;margin-bottom:6px}')
lines.append('.msg-bubble li{margin-bottom:2px}')
lines.append('.msg-bubble h1,.msg-bubble h2,.msg-bubble h3{font-family:"Space Mono",monospace;color:var(--text);margin:10px 0 6px;font-size:14px}')
lines.append('.msg-bubble strong{color:var(--text);font-weight:600}')
lines.append('.typing{display:flex;gap:4px;align-items:center;padding:4px 0}')
lines.append('.typing span{width:6px;height:6px;border-radius:50%;background:var(--text3);animation:bounce 1.2s ease-in-out infinite}')
lines.append('.typing span:nth-child(2){animation-delay:0.2s}.typing span:nth-child(3){animation-delay:0.4s}')
lines.append('@keyframes bounce{0%,60%,100%{transform:translateY(0)}30%{transform:translateY(-6px)}}')
lines.append('.input-area{padding:1rem 1.5rem 1.25rem;flex-shrink:0}')
lines.append('.input-wrap{display:flex;gap:8px;background:var(--bg3);border:1px solid var(--border2);border-radius:12px;padding:8px;transition:border-color 0.2s}')
lines.append('.input-wrap:focus-within{border-color:var(--accent)}')
lines.append('.chat-input{flex:1;background:none;border:none;outline:none;color:var(--text);font-size:15px;font-family:"DM Sans",sans-serif;resize:none;max-height:120px;line-height:1.5;padding:4px 6px}')
lines.append('.chat-input::placeholder{color:var(--text3)}')
lines.append('.send-btn{background:var(--accent);color:#fff;border:none;width:36px;height:36px;border-radius:8px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:opacity 0.15s;flex-shrink:0;align-self:flex-end}')
lines.append('.send-btn:hover:not(:disabled){opacity:0.85}')
lines.append('.send-btn:disabled{opacity:0.4;cursor:not-allowed}')
lines.append('.input-hint{font-size:11px;color:var(--text3);margin-top:6px;text-align:center}')
lines.append('.welcome{text-align:center;padding:3rem 1rem;color:var(--text2)}')
lines.append('.welcome h2{font-family:"Space Mono",monospace;font-size:18px;color:var(--text);margin-bottom:0.75rem}')
lines.append('.welcome p{font-size:14px;margin-bottom:1.5rem;max-width:480px;margin-left:auto;margin-right:auto}')
lines.append('.suggestions{display:flex;flex-wrap:wrap;gap:8px;justify-content:center}')
lines.append('.suggestion{background:var(--bg3);border:1px solid var(--border);border-radius:8px;padding:8px 14px;font-size:13px;cursor:pointer;transition:border-color 0.15s,color 0.15s;color:var(--text2)}')
lines.append('.suggestion:hover{border-color:var(--accent);color:var(--text)}')
lines.append('.auth-wrap{flex:1;display:flex;align-items:center;justify-content:center}')
lines.append('.auth-card{background:var(--bg3);border:1px solid var(--border2);border-radius:16px;padding:2.5rem;width:100%;max-width:400px;text-align:center}')
lines.append('.auth-logo{width:48px;height:48px;background:var(--accent);border-radius:12px;display:flex;align-items:center;justify-content:center;font-family:"Space Mono",monospace;font-size:16px;font-weight:700;color:#fff;margin:0 auto 1.25rem}')
lines.append('.auth-card h2{font-family:"Space Mono",monospace;font-size:18px;margin-bottom:0.5rem}')
lines.append('.auth-card p{color:var(--text2);font-size:14px;margin-bottom:1.5rem}')
lines.append('.field{margin-bottom:1rem;text-align:left}')
lines.append('.field label{display:block;font-size:12px;color:var(--text2);margin-bottom:5px}')
lines.append('.field input{width:100%;background:var(--bg2);border:1px solid var(--border2);color:var(--text);padding:10px 14px;border-radius:8px;font-size:14px;font-family:"DM Sans",sans-serif;outline:none}')
lines.append('.field input:focus{border-color:var(--accent)}')
lines.append('.btn{background:var(--accent);color:#fff;border:none;padding:11px;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;font-family:"DM Sans",sans-serif;width:100%;transition:opacity 0.15s}')
lines.append('.btn:hover{opacity:0.85}')
lines.append('.err{color:var(--poor);font-size:12px;margin-top:6px;padding:6px 10px;background:rgba(239,68,68,0.1);border-radius:6px}')
lines.append('</style>')
lines.append('</head>')
lines.append('<body>')
lines.append('<nav>')
lines.append('  <a class="nav-brand" href="https://edgeposture.ai"><div class="nav-logo">EP</div><span class="nav-title">EdgePosture AI</span></a>')
lines.append('  <span class="nav-badge">Workers AI</span>')
lines.append('  <div class="nav-right">')
lines.append('    <span class="rate-info" id="rate-info"></span>')
lines.append('    <a class="nav-link" href="https://edgepostureapp.com">Scanner</a>')
lines.append('    <a class="nav-link" href="https://edgeposture.ai">Home</a>')
lines.append('    <button class="nav-link" id="btn-logout" style="display:none">Sign out</button>')
lines.append('  </div>')
lines.append('</nav>')
lines.append('<div class="app-body" id="app-body">')
lines.append('  <!-- auth gate -->')
lines.append('  <div class="auth-wrap" id="auth-wrap">')
lines.append('    <div class="auth-card">')
lines.append('      <div class="auth-logo">EP</div>')
lines.append('      <h2>Sign in to continue</h2>')
lines.append('      <p>EdgePosture AI is available to registered users.</p>')
lines.append('      <div class="field"><label>Email</label><input type="email" id="auth-email" placeholder="you@example.com"/></div>')
lines.append('      <div class="field"><label>Password</label><input type="password" id="auth-password" placeholder="Your password"/></div>')
lines.append('      <div id="auth-err"></div>')
lines.append('      <button class="btn" id="login-btn">Sign in</button>')
lines.append('      <p style="margin-top:1rem;font-size:13px;color:var(--text2)">No account? <a href="https://edgepostureapp.com" style="color:var(--accent2)">Create one free</a></p>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('  <!-- main chat (hidden until authed) -->')
lines.append('  <div id="chat-ui" style="display:none;flex:1;display:none;overflow:hidden;flex-direction:row">')
lines.append('    <div class="sidebar">')
lines.append('      <div class="sidebar-header"><button class="new-chat-btn" id="new-chat-btn">+ New chat</button></div>')
lines.append('      <div class="sidebar-label">Recent chats</div>')
lines.append('      <div class="sessions-list" id="sessions-list"><div class="sessions-empty">No chats yet</div></div>')
lines.append('    </div>')
lines.append('    <div class="chat-main">')
lines.append('      <div class="messages" id="messages"></div>')
lines.append('      <div class="input-area">')
lines.append('        <div class="input-wrap">')
lines.append('          <textarea class="chat-input" id="chat-input" placeholder="Ask anything about security, CDN, performance, or web architecture..." rows="1"></textarea>')
lines.append('          <button class="send-btn" id="send-btn" disabled>')
lines.append('            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>')
lines.append('          </button>')
lines.append('        </div>')
lines.append('        <div class="input-hint">Enter to send &middot; Shift+Enter for new line &middot; <span id="remaining-hint"></span></div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</div>')
lines.append('<script>')
lines.append('var API="https://chat-api.edgeposture.ai";')
lines.append('var tok=localStorage.getItem("ep_token")||null;')
lines.append('var currentSessionId=null;')
lines.append('var waiting=false;')
lines.append('')
lines.append('function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}')
lines.append('function fmtDate(d){var now=new Date(),dt=new Date(d),diff=Math.floor((now-dt)/60000);if(diff<1)return "just now";if(diff<60)return diff+"m ago";if(diff<1440)return Math.floor(diff/60)+"h ago";return dt.toLocaleDateString();}')
lines.append('')
lines.append('function mdToHtml(s){')
lines.append('  if(!s)return "";')
lines.append('  var ls=s.split("\\n"),out=[],inPre=false,buf="";')
lines.append('  for(var i=0;i<ls.length;i++){')
lines.append('    var l=ls[i];')
lines.append('    if(l.indexOf("```")===0){if(inPre){out.push(buf+"</code></pre>");buf="";inPre=false;}else{inPre=true;buf="<pre><code>";}continue;}')
lines.append('    if(inPre){buf+=esc(l)+"\\n";continue;}')
lines.append('    if(l.indexOf("### ")===0){out.push("<h3>"+l.slice(4)+"</h3>");continue;}')
lines.append('    if(l.indexOf("## ")===0){out.push("<h2>"+l.slice(3)+"</h2>");continue;}')
lines.append('    if(l.indexOf("# ")===0){out.push("<h1>"+l.slice(2)+"</h1>");continue;}')
lines.append('    if(l.indexOf("- ")===0){out.push("<li>"+l.slice(2)+"</li>");continue;}')
lines.append('    if(l.indexOf("> ")===0){out.push("<blockquote>"+l.slice(2)+"</blockquote>");continue;}')
lines.append('    if(l===""){if(buf){out.push("<p>"+buf+"</p>");buf="";}continue;}')
lines.append('    l=l.replace(/`([^`]+)`/g,"<code>$1</code>");')
lines.append('    l=l.replace(/[*][*]([^*]+)[*][*]/g,"<strong>$1</strong>");')
lines.append('    l=l.replace(/[*]([^*]+)[*]/g,"<em>$1</em>");')
lines.append('    buf+=buf?" "+l:l;')
lines.append('  }')
lines.append('  if(buf)out.push("<p>"+buf+"</p>");')
lines.append('  return out.join("\\n");')
lines.append('}')
lines.append('')
lines.append('function addMsg(role,content,blocked){')
lines.append('  var msgs=document.getElementById("messages");')
lines.append('  var div=document.createElement("div");')
lines.append('  div.className="msg "+(blocked?"blocked":role);')
lines.append('  var bubble=role==="user"?"<p>"+esc(content)+"</p>":mdToHtml(content);')
lines.append('  div.innerHTML="<div class=\\"msg-avatar\\">"+(role==="user"?"ME":"EP")+"</div><div class=\\"msg-bubble\\">"+bubble+"</div>";')
lines.append('  msgs.appendChild(div);')
lines.append('  msgs.scrollTop=msgs.scrollHeight;')
lines.append('}')
lines.append('')
lines.append('function addTyping(){')
lines.append('  var msgs=document.getElementById("messages");')
lines.append('  var div=document.createElement("div");')
lines.append('  div.className="msg assistant";div.id="typing-ind";')
lines.append('  div.innerHTML="<div class=\\"msg-avatar\\">EP</div><div class=\\"msg-bubble\\"><div class=\\"typing\\"><span></span><span></span><span></span></div></div>";')
lines.append('  msgs.appendChild(div);msgs.scrollTop=msgs.scrollHeight;')
lines.append('}')
lines.append('function removeTyping(){var t=document.getElementById("typing-ind");if(t)t.remove();}')
lines.append('')
lines.append('function showWelcome(){')
lines.append('  var s=["How do I add security headers?","What is a CDN and how does it work?","Explain TTFB and how to improve it","What is a WAF and do I need one?","How does HTTPS/TLS work?","What is zero trust architecture?","Explain edge computing","How do I improve Core Web Vitals?"];')
lines.append('  var sh=s.map(function(x){return "<button class=\\"suggestion\\" onclick=\\"sendSuggestion(\'"+x.replace(/\'/g,"\\\\\'")+"\')\\">"+x+"</button>";}).join("");')
lines.append('  document.getElementById("messages").innerHTML="<div class=\\"welcome\\"><h2>EdgePosture AI Assistant</h2><p>Ask me anything about web security, CDN architecture, application performance, compliance, or edge computing.</p><div class=\\"suggestions\\">"+sh+"</div></div>";')
lines.append('}')
lines.append('')
lines.append('function sendSuggestion(s){document.getElementById("chat-input").value=s;sendMessage();}')
lines.append('')
lines.append('async function loadSessions(){')
lines.append('  try{')
lines.append('    var r=await fetch(API+"/sessions",{headers:{Authorization:"Bearer "+tok}});')
lines.append('    var d=await r.json();')
lines.append('    renderSessions(d.sessions||[]);')
lines.append('  }catch(e){}')
lines.append('}')
lines.append('')
lines.append('function renderSessions(sessions){')
lines.append('  var el=document.getElementById("sessions-list");')
lines.append('  if(!sessions.length){el.innerHTML="<div class=\\"sessions-empty\\">No chats yet</div>";return;}')
lines.append('  el.innerHTML=sessions.map(function(s){')
lines.append('    var active=s.id===currentSessionId?"active":"";')
lines.append('    return "<div class=\\"session-item "+active+"\\" id=\\"s-"+s.id+"\\" onclick=\\"loadSession(\'"+s.id+"\')\\">"')
lines.append('      +"<div class=\\"session-title\\">"+esc(s.title)+"</div>"')
lines.append('      +"<button class=\\"session-del\\" onclick=\\"event.stopPropagation();delSession(\'"+s.id+"\')\\" title=\\"Delete\\">&times;</button>"')
lines.append('      +"</div>";')
lines.append('  }).join("");')
lines.append('}')
lines.append('')
lines.append('async function loadSession(id){')
lines.append('  currentSessionId=id;')
lines.append('  document.getElementById("messages").innerHTML="";')
lines.append('  try{')
lines.append('    var r=await fetch(API+"/sessions/"+id,{headers:{Authorization:"Bearer "+tok}});')
lines.append('    var d=await r.json();')
lines.append('    var msgs=d.session.messages||[];')
lines.append('    msgs.forEach(function(m){addMsg(m.role,m.content,false);});')
lines.append('    loadSessions();')
lines.append('  }catch(e){addMsg("assistant","Failed to load session.",false);}')
lines.append('}')
lines.append('')
lines.append('async function delSession(id){')
lines.append('  if(!confirm("Delete this chat?"))return;')
lines.append('  await fetch(API+"/sessions/"+id,{method:"DELETE",headers:{Authorization:"Bearer "+tok}});')
lines.append('  if(currentSessionId===id){currentSessionId=null;showWelcome();}')
lines.append('  loadSessions();')
lines.append('}')
lines.append('')
lines.append('function newChat(){currentSessionId=null;showWelcome();loadSessions();}')
lines.append('')
lines.append('async function sendMessage(){')
lines.append('  if(waiting)return;')
lines.append('  var inp=document.getElementById("chat-input");')
lines.append('  var msg=inp.value.trim();')
lines.append('  if(!msg)return;')
lines.append('  inp.value="";inp.style.height="auto";')
lines.append('  document.getElementById("send-btn").disabled=true;')
lines.append('  waiting=true;')
lines.append('  var w=document.querySelector(".welcome");if(w)w.remove();')
lines.append('  addMsg("user",msg,false);')
lines.append('  addTyping();')
lines.append('  try{')
lines.append('    var r=await fetch(API+"/chat",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+tok},body:JSON.stringify({message:msg,sessionId:currentSessionId})});')
lines.append('    var d=await r.json();')
lines.append('    removeTyping();')
lines.append('    if(r.status===401){logout();return;}')
lines.append('    if(r.status===429){addMsg("assistant",d.error||"Rate limit reached.",false);return;}')
lines.append('    if(d.error){addMsg("assistant","Error: "+d.error,false);return;}')
lines.append('    addMsg("assistant",d.reply,d.blocked||false);')
lines.append('    if(d.sessionId){currentSessionId=d.sessionId;loadSessions();}')
lines.append('    if(d.remaining!==undefined){document.getElementById("rate-info").textContent=d.remaining+" left this hour";document.getElementById("remaining-hint").textContent=d.remaining+" messages left this hour";}')
lines.append('  }catch(e){removeTyping();addMsg("assistant","Connection error. Please try again.",false);}')
lines.append('  finally{waiting=false;document.getElementById("send-btn").disabled=false;inp.focus();}')
lines.append('}')
lines.append('')
lines.append('async function doLogin(){')
lines.append('  var email=document.getElementById("auth-email").value.trim();')
lines.append('  var pw=document.getElementById("auth-password").value;')
lines.append('  var err=document.getElementById("auth-err");')
lines.append('  if(!email||!pw){err.innerHTML="<div class=\\"err\\">Email and password required</div>";return;}')
lines.append('  try{')
lines.append('    var r=await fetch("https://api.edgepostureapp.com/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email,password:pw})});')
lines.append('    var d=await r.json();')
lines.append('    if(!r.ok){err.innerHTML="<div class=\\"err\\">"+(d.error||"Invalid credentials")+"</div>";return;}')
lines.append('    tok=d.token;localStorage.setItem("ep_token",tok);')
lines.append('    showChat();')
lines.append('  }catch(e){err.innerHTML="<div class=\\"err\\">Connection error</div>";}')
lines.append('}')
lines.append('')
lines.append('function logout(){')
lines.append('  tok=null;localStorage.removeItem("ep_token");')
lines.append('  document.getElementById("btn-logout").style.display="none";')
lines.append('  document.getElementById("chat-ui").style.display="none";')
lines.append('  document.getElementById("auth-wrap").style.display="flex";')
lines.append('}')
lines.append('')
lines.append('function showChat(){')
lines.append('  document.getElementById("auth-wrap").style.display="none";')
lines.append('  var ui=document.getElementById("chat-ui");')
lines.append('  ui.style.display="flex";ui.style.flex="1";ui.style.flexDirection="row";')
lines.append('  document.getElementById("btn-logout").style.display="block";')
lines.append('  loadSessions();')
lines.append('  showWelcome();')
lines.append('}')
lines.append('')
lines.append('var inp=document.getElementById("chat-input");')
lines.append('inp.addEventListener("input",function(){this.style.height="auto";this.style.height=Math.min(this.scrollHeight,120)+"px";document.getElementById("send-btn").disabled=!this.value.trim()||waiting;});')
lines.append('inp.addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage();}});')
lines.append('document.getElementById("send-btn").onclick=sendMessage;')
lines.append('document.getElementById("btn-logout").onclick=logout;')
lines.append('document.getElementById("new-chat-btn").onclick=newChat;')
lines.append('document.getElementById("login-btn").onclick=doLogin;')
lines.append('document.getElementById("auth-email").onkeydown=function(e){if(e.key==="Enter")document.getElementById("auth-password").focus();};')
lines.append('document.getElementById("auth-password").onkeydown=function(e){if(e.key==="Enter")doLogin();};')
lines.append('if(tok){showChat();}')
lines.append('</script>')
lines.append('</body>')
lines.append('</html>')

with open('C:/Users/miked/edgeposture/chat-frontend/index.html', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('Chat UI with history written successfully')