content = open('C:/Users/miked/edgeposture/worker-api/src/auth.js', 'w', encoding='utf-8')
content.write("export async function handleAuth(request, env, action) {\n")
content.write("  if (action === 'login') {\n")
content.write("    const { email, password } = await request.json();\n")
content.write("    if (!email || !password) throw new Error('Email and password required');\n")
content.write("    const user = await env.DB.prepare('SELECT * FROM users WHERE email = ?').bind(email.toLowerCase()).first();\n")
content.write("    if (!user) throw new Error('Invalid credentials');\n")
content.write("    const valid = await verifyPassword(password, user.password_hash);\n")
content.write("    if (!valid) throw new Error('Invalid credentials');\n")
content.write("    const token = await createToken({ id: user.id, email: user.email }, env.JWT_SECRET);\n")
content.write("    return { token, user: { id: user.id, email: user.email, name: user.name } };\n")
content.write("  }\n")
content.write("  if (action === 'register') {\n")
content.write("    const { email, password, name } = await request.json();\n")
content.write("    if (!email || !password || !name) throw new Error('Name, email, and password required');\n")
content.write("    if (password.length < 8) throw new Error('Password must be at least 8 characters');\n")
content.write("    const existing = await env.DB.prepare('SELECT id FROM users WHERE email = ?').bind(email.toLowerCase()).first();\n")
content.write("    if (existing) throw new Error('Email already registered');\n")
content.write("    const id = crypto.randomUUID();\n")
content.write("    const hash = await hashPassword(password);\n")
content.write("    await env.DB.prepare('INSERT INTO users (id, email, name, password_hash, created_at) VALUES (?, ?, ?, ?, ?)').bind(id, email.toLowerCase(), name, hash, new Date().toISOString()).run();\n")
content.write("    const token = await createToken({ id, email: email.toLowerCase() }, env.JWT_SECRET);\n")
content.write("    return { token, user: { id, email: email.toLowerCase(), name } };\n")
content.write("  }\n")
content.write("  if (action === 'me') {\n")
content.write("    const user = await requireAuth(request, env);\n")
content.write("    return { user };\n")
content.write("  }\n")
content.write("}\n\n")
content.write("export async function requireAuth(request, env) {\n")
content.write("  const auth = request.headers.get('Authorization');\n")
content.write("  if (!auth || !auth.startsWith('Bearer ')) throw new Error('Authentication required');\n")
content.write("  const token = auth.slice(7);\n")
content.write("  const payload = await verifyToken(token, env.JWT_SECRET);\n")
content.write("  if (!payload) throw new Error('Invalid or expired token');\n")
content.write("  const user = await env.DB.prepare('SELECT id, email, name FROM users WHERE id = ?').bind(payload.id).first();\n")
content.write("  if (!user) throw new Error('User not found');\n")
content.write("  return user;\n")
content.write("}\n\n")
content.write("async function hashPassword(password) {\n")
content.write("  const encoder = new TextEncoder();\n")
content.write("  const salt = crypto.getRandomValues(new Uint8Array(16));\n")
content.write("  const keyMaterial = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);\n")
content.write("  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: 100000, hash: 'SHA-256' }, keyMaterial, 256);\n")
content.write("  const hashArray = new Uint8Array(bits);\n")
content.write("  return btoa(String.fromCharCode(...salt)) + ':' + btoa(String.fromCharCode(...hashArray));\n")
content.write("}\n\n")
content.write("async function verifyPassword(password, stored) {\n")
content.write("  const [saltB64, hashB64] = stored.split(':');\n")
content.write("  const salt = Uint8Array.from(atob(saltB64), c => c.charCodeAt(0));\n")
content.write("  const encoder = new TextEncoder();\n")
content.write("  const keyMaterial = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);\n")
content.write("  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: 100000, hash: 'SHA-256' }, keyMaterial, 256);\n")
content.write("  const newHash = btoa(String.fromCharCode(...new Uint8Array(bits)));\n")
content.write("  return newHash === hashB64;\n")
content.write("}\n\n")
content.write("async function createToken(payload, secret) {\n")
content.write("  const encoder = new TextEncoder();\n")
content.write("  const header = btoa(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));\n")
content.write("  const body = btoa(JSON.stringify({ ...payload, exp: Math.floor(Date.now() / 1000) + 86400 * 30 }));\n")
content.write("  const data = `${header}.${body}`;\n")
content.write("  const key = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);\n")
content.write("  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(data));\n")
content.write("  return `${data}.${btoa(String.fromCharCode(...new Uint8Array(sig)))}`;\n")
content.write("}\n\n")
content.write("async function verifyToken(token, secret) {\n")
content.write("  try {\n")
content.write("    const [header, body, sig] = token.split('.');\n")
content.write("    const encoder = new TextEncoder();\n")
content.write("    const key = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['verify']);\n")
content.write("    const valid = await crypto.subtle.verify('HMAC', key, Uint8Array.from(atob(sig), c => c.charCodeAt(0)), encoder.encode(`${header}.${body}`));\n")
content.write("    if (!valid) return null;\n")
content.write("    const payload = JSON.parse(atob(body));\n")
content.write("    if (payload.exp < Math.floor(Date.now() / 1000)) return null;\n")
content.write("    return payload;\n")
content.write("  } catch { return null; }\n")
content.write("}\n")
content.close()
print('Done')